vich_uploader:
    db_driver: orm

    mappings:
        property:
            uri_prefix: /images/properties
            upload_destination: "%kernel.project_dir%/public/images/properties"
        picture:
            uri_prefix: /images/global
            upload_destination: "%kernel.project_dir%/public/images/global"